name: Run Pytest on Branches

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Apt install dependencies
        run: |
          sudo apt-get update
          sudo apt install tesseract-ocr
          sudo apt install libtesseract-dev
          sudo apt-get install ffmpeg
          sudo apt install antiword
          sudo apt install libreoffice

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --disable-warnings .

      - name: Test Code Coverage
        run: pytest --cov=querent
