name: Run Pytest on Branches

on:
  push:
    branches:
      - '*'
      - main
    paths-ignore:
      - 'README.md'  # Add any paths you want to exclude

jobs:
  pytest:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Apt install dependencies
        run: |
          sudo apt install tesseract-ocr -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --disable-warnings .
